version: "3"
name: minesweeper
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    # command: bash -c "./bin/dev"
    command: sh -c "rm -f tmp/pids/server.pid && bin/rails server -b '0.0.0.0'"
    tty: true
    volumes:
      - .:/rails
    ports:
      - "3000:3000"
    depends_on:
      - db
      # - redis

  db:
    image: nouchka/sqlite3:latest
    stdin_open: true
    tty: true
    volumes:
      - ./db_volume:/root/db

  # redis:
  #   image: redis:7.0-alpine
  #   ports:
  #     - 6379:6379
