version: "3"
name: minesweeper
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "rm -f tmp/pids/server.pid && bin/rails server -b '0.0.0.0'"
    tty: true
    volumes:
      - .:/rails
    ports:
      - "3000:3000"
    env_file:
      - web.env
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: minesweeper_dev
    ports:
      - "3306:3306"
    volumes:
      - ./db_volume/mysql_data:/var/lib/mysql
      - ./db_volume/mysql_config/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
